from django.shortcuts import render

# Create your views here.
def prodi9(request):
    judul = ["DOKTOR PENDIDIKAN", "DOKTOR ILMU AKUNTANSI", "DOKTOR ILMU PERTANIAN", "PENDIDIKAN BAHASA INDONESIA", "MAGISTER ILMU HUKUM", "MAGISTER ILMU PERTANIAN", "MAGISTER ADMINISTRASI PUBLIK", "MAGISTER AKUNTANSI", "MAGISTER ILMU KOMUNIKASI", "MAGISTER MANAJEMEN", "MAGISTER TEKNIK KIMIA", "MAGISTER PENDIDIDKAN DASAR", "PENDIDIKAN BAHASA INGGRIS", "PENDIDIKAN MATEMATIKA", "TEKNOLOGI PENDIDIKAN", "MAGISTER EKONOMI"]

    konteks = {
        'title' : judul,
    }
  
    return render(request, 'pascasarjana.html', konteks)
